name: Release

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3

      - name: Install dependencies
        run: python -m pip install --upgrade pip build

      - name: Build Python package
        run: python -m build

      - name: Upload Python packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python Packages
          path: dist

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
